import { useEffect, useState } from "react";

const VITE_API_BASE_URL = import.meta.env.VITE_API_BASE_URL;

const SAMPLE_URLS = [
  "https://en.wikipedia.org/wiki/History_of_India",
  "https://en.wikipedia.org/wiki/Web_scraping",
];

function normalizeUrl(value) {
  const trimmed = value.trim();
  if (!trimmed) return "";
  return /^https?:\/\//i.test(trimmed) ? trimmed : `https://${trimmed}`;
}

function storedTheme() {
  try {
    return localStorage.getItem("theme");
  } catch {
    return null;
  }
}

export default function App() {
  const [url, setUrl] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);
  const [copied, setCopied] = useState(false);
  const [theme, setTheme] = useState(
    () => document.documentElement.dataset.theme || storedTheme() || "dark",
  );

  useEffect(() => {
    setCopied(false);
  }, [result]);

  function toggleTheme() {
    setTheme((prev) => {
      const next = prev === "dark" ? "light" : "dark";
      document.documentElement.dataset.theme = next;
      try {
        localStorage.setItem("theme", next);
      } catch {
        /* storage unavailable - theme just won't persist */
      }
      return next;
    });
  }

  async function handleCopy() {
    if (!result) return;
    try {
      await navigator.clipboard.writeText(result.summary);
      setCopied(true);
    } catch {
      setError(
        "Could not copy to the clipboard - your browser blocked the request.",
      );
    }
  }

  function handleDownload() {
    if (!result) return;
    const header = [
      result.title || "Untitled page",
      `Source: ${result.url}`,
      `Generated by AI Web Scraper (${result.provider} \u00b7 ${result.model})`,
      "",
      "--- SUMMARY ---",
      "",
    ].join("\n");
    const blob = new Blob([header, result.summary, "\n"], {
      type: "text/plain;charset=utf-8",
    });
    const href = URL.createObjectURL(blob);
    const slug = (result.title || "summary")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 60);
    const anchor = document.createElement("a");
    anchor.href = href;
    anchor.download = `${slug || "summary"}.txt`;
    document.body.appendChild(anchor);
    anchor.click();
    anchor.remove();
    setTimeout(() => URL.revokeObjectURL(href), 1000);
  }

  async function handleSubmit(event) {
    event.preventDefault();
    const target = normalizeUrl(url);
    if (!target) {
      setError("Paste a webpage URL to summarize.");
      return;
    }

    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const res = await fetch(`${VITE_API_BASE_URL}/api/summarize`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ url: target }),
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        throw new Error(
          data.error || `Request failed with status ${res.status}.`,
        );
      }
      setResult(data);
    } catch (err) {
      setError(
        err.message ||
          "Could not reach the backend. Make sure it is runnning and that you have an internet connection.",
      );
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="page">
      <div className="topbar">
        <button
          type="button"
          className="theme-toggle"
          onClick={toggleTheme}
          aria-label="Toggle color theme"
        >
          {theme === "dark" ? "\u2600\ufe0f" : "\u{1F319}"}{" "}
          <span>{theme === "dark" ? "Light" : "Dark"} mode</span>
        </button>
      </div>
      <header className="hero">
        <span className="hero-badge">Full-stack demo</span>
        <h1>
          AI Web <span className="accent">Scraper</span>
        </h1>
        <p className="tagline">
          Paste any webpage URL. The backend scrapes the main text and a free AI
          model turns it into a short summary.
        </p>
      </header>

      <section className="card">
        <form onSubmit={handleSubmit} className="url-form">
          <input
            type="text"
            inputMode="url"
            className="url-input"
            name="url"
            autoComplete="url"
            placeholder="https://example.com/article"
            value={url}
            onChange={(e) => setUrl(e.target.value)}
            disabled={loading}
            aria-label="Webpage URL"
          />
          <button type="submit" className="summarize-btn" disabled={loading}>
            {loading ? (
              <>
                <span className="spinner" aria-hidden="true" />
                Summarizing…
              </>
            ) : (
              "Summarize"
            )}
          </button>
        </form>

        <div className="samples">
          <span>Try:</span>
          {SAMPLE_URLS.map((sample) => (
            <button
              key={sample}
              type="button"
              className="sample-chip"
              disabled={loading}
              onClick={() => setUrl(sample)}
            >
              {sample.replace(/^https?:\/\//, "").replace(/\/$/, "")}
            </button>
          ))}
        </div>
      </section>

      {loading && (
        <section className="card status-card" role="status" aria-live="polite">
          <div className="status-line">
            <span className="spinner" aria-hidden="true" />
            <div>
              <h2>Working on it…</h2>
              <p>
                Fetching the page, extracting text, and asking AI to summarize.
              </p>
            </div>
          </div>
          <div className="skeleton">
            <span />
            <span />
            <span style={{ width: "65%" }} />
          </div>
        </section>
      )}

      {error && !loading && (
        <section className="card error-card" role="alert">
          <h2>Something went wrong</h2>
          <p>{error}</p>
        </section>
      )}

      {result && !loading && (
        <section className="card result-card">
          <div className="result-head">
            <h2>{result.title || "Untitled page"}</h2>
            <a
              href={result.url}
              target="_blank"
              rel="noreferrer"
              className="source-link"
            >
              {result.url}
            </a>
          </div>

          <div className="meta-row">
            <span className="chip chip-ai">
              {result.provider} · {result.model}
            </span>
            <span className="chip">
              {result.scrapedChars.toLocaleString()} chars scraped
            </span>
            <span className="chip">
              {(result.elapsedMs / 1000).toFixed(1)}s
            </span>
            {result.truncated && (
              <span className="chip chip-warn">text truncated</span>
            )}
          </div>

          <div className="result-actions">
            <button
              type="button"
              className={`action-btn${copied ? " action-btn-done" : ""}`}
              onClick={handleCopy}
            >
              {copied ? "Copied \u2713" : "Copy summary"}
            </button>
            <button
              type="button"
              className="action-btn"
              onClick={handleDownload}
            >
              Download .txt
            </button>
          </div>

          <p className="summary">{result.summary}</p>
        </section>
      )}

      <footer className="footer">
        RAJAT SHARMA | Made with ❤️ · Google Gemini · React (Vite) · Node.js
        (Express)
      </footer>
    </div>
  );
}
